name: Pull Request Review
on: pull_request

jobs:
  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v3

      # Install Node 16
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      # Install NPM Package Dependencies
      - name: Install Package Dependencies
        run: npm install

      # Cache node modules
      - name: Cache node_modules
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-$GITHUB_RUN_ID

  unit_tests:
    name: Unit Tests
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      # Get node_modules from the cache
      - name: Load Cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-$GITHUB_RUN_ID

      # Checkout the Repo
      - uses: actions/checkout@v3

      # Run unit tests
      - name: Run Unit Tests
        run: npm test